(() => {
  const root = window.N3App || (window.N3App = {});
  const constants = root.constants || (root.constants = {});
  constants.MEMORY_EVENT_TYPES = new Set([
    "memory_recall",
    "memory_write",
    "memory_denied",
    "memory_forget",
    "memory_conflict",
    "memory_border_check",
    "memory_promoted",
    "memory_promotion_denied",
    "memory_phase_started",
    "memory_deleted",
    "memory_phase_diff",
    "memory_links",
    "memory_path",
    "memory_impact",
    "memory_change_preview",
    "memory_team_summary",
    "memory_proposed",
    "memory_approved",
    "memory_rejected",
    "memory_agreement_summary",
    "memory_trust_check",
    "memory_approval_recorded",
    "memory_trust_rules",
    "memory_rule_applied",
    "memory_rules_snapshot",
    "memory_rule_changed",
    "memory_budget",
    "memory_compaction",
    "memory_cache_hit",
    "memory_cache_miss",
    "memory_wake_up_report",
    "memory_restore_failed",
    "memory_pack_loaded",
    "memory_pack_merged",
    "memory_pack_overrides",
    "memory_handoff_created",
    "memory_handoff_applied",
    "memory_handoff_rejected",
    "memory_agent_briefing",
  ]);
  constants.PREFERRED_SEED_ACTIONS = [
    "seed",
    "seed_data",
    "seed_demo",
    "demo_seed",
    "seed_customers",
  ];
})();
