name: Feature discussion
description: Propose or discuss a feature
title: "[idea] "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        namel3ss is opinionated.
        Please explain the *problem*, not just the solution.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: How do you solve this today?
