from __future__ import annotations

from namel3ss.parser.presets.rag_chat import (
    DEFAULT_RAG_CHAT_MODEL,
    DEFAULT_RAG_CHAT_SYSTEM_PROMPT,
    DEFAULT_RAG_CHAT_TEMPERATURE,
    RAG_CHAT_TEMPLATE_PLAIN_CONCISE,
    RAG_CHAT_TEMPLATE_SUMMARY_KEYPOINTS_RECOMMENDATION_WITH_CITATIONS,
    SUPPORTED_RAG_CHAT_ANSWER_TEMPLATES,
    RagChatPresetConfig,
    render_rag_chat_source,
)
from namel3ss.parser.presets.agent_workspace import (
    AGENT_WORKSPACE_PATTERN_PLANNER_EXECUTOR,
    AGENT_WORKSPACE_PATTERN_RESEARCH_RAG,
    AGENT_WORKSPACE_PATTERN_ROUTER_SPECIALISTS,
    AGENT_WORKSPACE_PATTERN_SINGLE_AGENT,
    DEFAULT_AGENT_WORKSPACE_MODEL,
    DEFAULT_AGENT_WORKSPACE_SYSTEM_PROMPT,
    DEFAULT_AGENT_WORKSPACE_TEMPERATURE,
    SUPPORTED_AGENT_WORKSPACE_OVERRIDE_FLOWS,
    SUPPORTED_AGENT_WORKSPACE_PATTERNS,
    AgentWorkspacePresetConfig,
    render_agent_workspace_source,
)

__all__ = [
    "RagChatPresetConfig",
    "render_rag_chat_source",
    "SUPPORTED_RAG_CHAT_ANSWER_TEMPLATES",
    "RAG_CHAT_TEMPLATE_PLAIN_CONCISE",
    "RAG_CHAT_TEMPLATE_SUMMARY_KEYPOINTS_RECOMMENDATION_WITH_CITATIONS",
    "DEFAULT_RAG_CHAT_MODEL",
    "DEFAULT_RAG_CHAT_TEMPERATURE",
    "DEFAULT_RAG_CHAT_SYSTEM_PROMPT",
    "AgentWorkspacePresetConfig",
    "render_agent_workspace_source",
    "SUPPORTED_AGENT_WORKSPACE_PATTERNS",
    "AGENT_WORKSPACE_PATTERN_SINGLE_AGENT",
    "AGENT_WORKSPACE_PATTERN_ROUTER_SPECIALISTS",
    "AGENT_WORKSPACE_PATTERN_PLANNER_EXECUTOR",
    "AGENT_WORKSPACE_PATTERN_RESEARCH_RAG",
    "DEFAULT_AGENT_WORKSPACE_MODEL",
    "DEFAULT_AGENT_WORKSPACE_TEMPERATURE",
    "DEFAULT_AGENT_WORKSPACE_SYSTEM_PROMPT",
    "SUPPORTED_AGENT_WORKSPACE_OVERRIDE_FLOWS",
]
