from __future__ import annotations

from namel3ss.parser.presets.rag_chat import (
    DEFAULT_RAG_CHAT_MODEL,
    DEFAULT_RAG_CHAT_SYSTEM_PROMPT,
    DEFAULT_RAG_CHAT_TEMPERATURE,
    RAG_CHAT_TEMPLATE_PLAIN_CONCISE,
    RAG_CHAT_TEMPLATE_SUMMARY_KEYPOINTS_RECOMMENDATION_WITH_CITATIONS,
    SUPPORTED_RAG_CHAT_ANSWER_TEMPLATES,
    RagChatPresetConfig,
    render_rag_chat_source,
)

__all__ = [
    "RagChatPresetConfig",
    "render_rag_chat_source",
    "SUPPORTED_RAG_CHAT_ANSWER_TEMPLATES",
    "RAG_CHAT_TEMPLATE_PLAIN_CONCISE",
    "RAG_CHAT_TEMPLATE_SUMMARY_KEYPOINTS_RECOMMENDATION_WITH_CITATIONS",
    "DEFAULT_RAG_CHAT_MODEL",
    "DEFAULT_RAG_CHAT_TEMPERATURE",
    "DEFAULT_RAG_CHAT_SYSTEM_PROMPT",
]
