from __future__ import annotations


def build_rag_chat_pre_override_lines() -> list[str]:
    return [
        '  if context_text is "":',
        "    if question_upload_count is greater than 0:",
        "      let attachment_upload_ids is list:",
        "      for each upload_item in question_upload_entries:",
        '        let attachment_upload_id is ""',
        "        try:",
        "          let candidate_upload_id is upload_item.id",
        '          if candidate_upload_id is not "":',
        "            set attachment_upload_id is candidate_upload_id",
        "        with catch err:",
        "          set attachment_upload_id is attachment_upload_id",
        '        if attachment_upload_id is "":',
        "          try:",
        "            let fallback_upload_id is upload_item.upload_id",
        '            if fallback_upload_id is not "":',
        "              set attachment_upload_id is fallback_upload_id",
        "          with catch err:",
        "            set attachment_upload_id is attachment_upload_id",
        '        if attachment_upload_id is "":',
        "          try:",
        "            let fallback_checksum is upload_item.checksum",
        '            if fallback_checksum is not "":',
        "              set attachment_upload_id is fallback_checksum",
        "          with catch err:",
        "            set attachment_upload_id is attachment_upload_id",
        '        if attachment_upload_id is not "":',
        "          set attachment_upload_ids is list append attachment_upload_ids with attachment_upload_id",
        "      try:",
        "        let known_index is state.index",
        '        let known_chunks is map get known_index key "chunks"',
        "        for each known_chunk in known_chunks:",
        '          let known_upload_id is ""',
        "          try:",
        "            let chunk_upload_id is known_chunk.upload_id",
        '            if chunk_upload_id is not "":',
        "              set known_upload_id is chunk_upload_id",
        "          with catch err:",
        "            set known_upload_id is known_upload_id",
        '          if known_upload_id is not "":',
        "            let in_attachment_scope is false",
        "            for each attachment_upload_id in attachment_upload_ids:",
        "              if attachment_upload_id is known_upload_id:",
        "                set in_attachment_scope is true",
        "            if in_attachment_scope is true:",
        '              let snippet_text is ""',
        "              try:",
        "                let chunk_text is known_chunk.text",
        '                if chunk_text is not "":',
        "                  set snippet_text is chunk_text",
        "              with catch err:",
        "                set snippet_text is snippet_text",
        '              if snippet_text is not "":',
        '                if context_text is "":',
        '                  set context_text is "[1] " + snippet_text',
        "                  let citation_entry is map:",
        '                    "ref" is "[1]"',
        '                    "title" is known_chunk.source_name',
        '                    "source_id" is known_chunk.upload_id',
        '                    "chunk_id" is known_chunk.chunk_id',
        '                    "document_id" is known_chunk.upload_id',
        '                    "page_number" is 1',
        '                    "snippet" is snippet_text',
        '                    "url" is known_chunk.upload_id',
        '                    "preview_url" is "/api/documents/" + known_chunk.upload_id + "/pages/1?chunk_id=" + known_chunk.chunk_id',
        "                  set citations is list append citations with citation_entry",
        "      with catch err:",
        "        set context_text is context_text",
    ]


def build_rag_chat_suffix_lines(*, title: str, accept: str) -> list[str]:
    return [
        '  if context_text is "":',
        "    if has_pdf_question_upload is true:",
        '      set __rag_answer_text is "I could not extract readable text from the selected PDF source. Upload a text-searchable PDF (or OCR text), wait for indexing to finish, then ask again."',
        "    else:",
        '      set __rag_answer_text is "No grounded support found in indexed sources for this query."',
        "  else:",
        '    if __rag_answer_text is "":',
        "      set __rag_answer_text is context_text",
        '  let scope_indicator is ""',
        "  if question_upload_count is greater than 0:",
        '    set scope_indicator is "Scope: attached files"',
        "  let assistant_content is __rag_answer_text",
        '  if scope_indicator is not "":',
        '    set assistant_content is scope_indicator + "\\n" + __rag_answer_text',
        "  let messages is list:",
        "  try:",
        "    set messages is state.chat.messages",
        "  with catch err:",
        "    set messages is list:",
        "  let user_message is map:",
        '    "role" is "user"',
        '    "content" is query_text',
        "  let assistant_message is map:",
        '    "role" is "assistant"',
        '    "content" is assistant_content',
        '    "citations" is citations',
        "  set messages is list append messages with user_message",
        "  set messages is list append messages with assistant_message",
        "  set state.chat.messages is messages",
        "  set state.chat.citations is citations",
        "  if question_upload_count is greater than 0:",
        "    set state.uploads.chat_files is list:",
        "  return map:",
        '    "answer_text" is __rag_answer_text',
        '    "mode" is "ok"',
        '    "context" is context_text',
        '    "citations" is citations',
        "",
        'page "Chat":',
        "  layout:",
        '    sidebar_width is "wide"',
        '    panel_height is "full"',
        "    resizable_panels is false",
        "    header:",
        '      title is "RAG Workspace"',
        '      text is "Project-scoped knowledge and grounded answers."',
        "",
        "    sidebar_left:",
        '      section "Projects":',
        '        list is Project:',
        '          variant is "icon_plain"',
        "          item:",
        "            primary is name",
        "            secondary is status_label",
        "            icon is icon",
        "            icon_color is icon_color",
        "          empty_state: hidden",
        "          actions:",
        '            action "Open":',
        '              calls flow "rag.set_active_project"',
        '            action "Upload files":',
        '              calls flow "rag.set_active_project"',
        "              interaction is upload_picker",
        '            action "Rename":',
        '              calls flow "rag.rename_active_project"',
        "              interaction is rename_modal",
        '            action "Duplicate":',
        '              calls flow "rag.duplicate_project"',
        '            action "Share":',
        '              calls flow "rag.share_project"',
        '            action "Archive":',
        '              calls flow "rag.archive_project"',
        '            action "Delete project":',
        '              calls flow "rag.delete_project"',
        "              interaction is confirm_destructive",
        "",
        '        list is ProjectKnowledgeItem:',
        '          variant is "two_line"',
        "          group_by is project_id",
        "          group_label is project_name",
        "          item:",
        "            primary is source_name",
        "            secondary is status_label",
        "          empty_state: hidden",
        "          actions:",
        '            action "Rename file":',
        '              calls flow "rag.rename_document"',
        "              interaction is rename_modal",
        '            action "Move to project...":',
        '              calls flow "rag.move_document_to_project"',
        "              interaction is project_picker",
        '            action "Remove from project":',
        '              calls flow "rag.remove_document_from_project"',
        '            action "Delete file":',
        '              calls flow "rag.remove_document"',
        "              interaction is confirm_destructive",
        "",
        '        button "Create project":',
        "          icon is folder",
        '          variant is "primary"',
        '          calls flow "rag.create_project"',
        "",
        "        upload project_files:",
        f'          accept is "{accept}"',
        "          multiple is true",
        "          required is false",
        '          label is "Upload to active project"',
        "          preview is false",
        "",
        "    main:",
        f'      section "{title}":',
        "        row:",
        "          column:",
        '            button "Create chat":',
        "              icon is chat_add_on",
        '              variant is "secondary"',
        '              calls flow "rag.reset_chat"',
        "",
        "        chat:",
        '          style is "bubbles"',
        "          show_avatars is false",
        "          group_messages is true",
        '          actions are ["copy", "view_sources"]',
        "          attachments are true",
        "          streaming is false",
        '          composer_placeholder is "Ask a grounded question about this project..."',
        "          composer_send_style is icon",
        '          composer_attach_upload is "chat_files"',
        "          messages from is state.chat.messages",
        '          composer calls flow "rag.answer"',
        "          citations from is state.chat.citations",
        "",
        "        upload chat_files:",
        f'          accept is "{accept}"',
        "          multiple is true",
        "          required is false",
        '          label is "Attach files for this question"',
        "          preview is false",
    ]


__all__ = ["build_rag_chat_pre_override_lines", "build_rag_chat_suffix_lines"]
