from __future__ import annotations


def build_rag_chat_core_lines() -> list[str]:
    return [
        'record "Project":',
        "  id is text",
        "  name is text",
        "  status_label is text",
        "  icon is text",
        "  icon_color is text",
        "",
        'record "ProjectKnowledgeItem":',
        "  id is text",
        "  project_id is text",
        "  project_name is text",
        "  upload_id is text",
        "  source_name is text",
        "  status_label is text",
        "",
        'contract flow "rag.ensure_projects":',
        "  input:",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.create_project":',
        "  input:",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.set_active_project":',
        "  input:",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.rename_active_project":',
        "  input:",
        "    project_name is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.duplicate_project":',
        "  input:",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.share_project":',
        "  input:",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.archive_project":',
        "  input:",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.delete_project":',
        "  input:",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.rename_document":',
        "  input:",
        "    upload_id is optional text",
        "    source_name is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.move_document_to_project":',
        "  input:",
        "    upload_id is optional text",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.remove_document_from_project":',
        "  input:",
        "    upload_id is optional text",
        "    project_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.remove_document":',
        "  input:",
        "    upload_id is optional text",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.ingest":',
        "  input:",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.reset_chat":',
        "  input:",
        "  output:",
        "    status is text",
        "",
        'contract flow "rag.answer":',
        "  input:",
        "    message is text",
        "    query is optional text",
        "    query_text is optional text",
        "    context is optional text",
        "    project_scope is optional text",
        "    project_scope_label is optional text",
        "    project_scope_conflict is optional boolean",
        "    document_scope is optional json",
        "    document_scope_mode is optional text",
        "  output:",
        "    answer_text is text",
        "    mode is text",
        "    context is text",
        "    citations is json",
        "",
        'flow "rag.ensure_projects": requires true',
        '  set state.active_project_id is ""',
        '  set state.ui.active_project_id is ""',
        '  find "Project" where true',
        "  let project_count is list length of project_results",
        "  if project_count is 0:",
        '    create "Project" with map:',
        '      "id" is "project-1"',
        '      "name" is "Default Project"',
        '      "status_label" is "Active"',
        '      "icon" is "folder"',
        '      "icon_color" is "blue"',
        "    as default_project",
        '    set state.active_project_id is "project-1"',
        '    set state.ui.active_project_id is "project-1"',
        "  if project_count is greater than 0:",
        "    let first_project is list get project_results at 0",
        "    try:",
        "      let active_project_id is state.active_project_id",
        '      if active_project_id is not "":',
        '        find "Project" where id is active_project_id',
        "        let active_count is list length of project_results",
        "        if active_count is greater than 0:",
        "          let active_project is list get project_results at 0",
        "          set first_project is active_project",
        "    with catch err:",
        "      set first_project is first_project",
        "    set state.active_project_id is first_project.id",
        "    set state.ui.active_project_id is first_project.id",
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.set_active_project": requires true',
        '  let project_id is ""',
        "  try:",
        "    let requested_project_id is input.project_id",
        '    if requested_project_id is not "":',
        "      set project_id is requested_project_id",
        "  with catch err:",
        "    set project_id is project_id",
        "  try:",
        "    let row_project_id is input.row.id",
        '    if project_id is "":',
        '      if row_project_id is not "":',
        "        set project_id is row_project_id",
        "  with catch err:",
        "    set project_id is project_id",
        '  if project_id is "":',
        '    let ensure_status is call flow "rag.ensure_projects":',
        "      input:",
        "      output:",
        "        status",
        "    try:",
        "      let fallback_project_id is state.active_project_id",
        "      set project_id is fallback_project_id",
        "    with catch err:",
        "      set project_id is project_id",
        '  if project_id is not "":',
        "    set state.active_project_id is project_id",
        "    set state.ui.active_project_id is project_id",
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.create_project": requires true',
        '  let ensure_status is call flow "rag.ensure_projects":',
        "    input:",
        "    output:",
        "      status",
        '  find "Project" where true',
        "  let project_count is list length of project_results",
        "  let project_index is project_count + 1",
        '  let project_id is "project-" + project_index',
        '  let project_name is "Project " + project_index',
        '  create "Project" with map:',
        '    "id" is project_id',
        '    "name" is project_name',
        '    "status_label" is "Active"',
        '    "icon" is "folder"',
        '    "icon_color" is "blue"',
        "  as created_project",
        "  set state.active_project_id is project_id",
        "  set state.ui.active_project_id is project_id",
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.rename_active_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.duplicate_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.share_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.archive_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.delete_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.rename_document": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.move_document_to_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.remove_document_from_project": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.remove_document": requires true',
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.reset_chat": requires true',
        "  set state.chat.messages is list:",
        "  set state.chat.citations is list:",
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.ingest": requires true',
        '  let ensure_status is call flow "rag.ensure_projects":',
        "    input:",
        "    output:",
        "      status",
        "  let uploads is list:",
        "  try:",
        "    set uploads is state.uploads.project_files",
        "  with catch err:",
        "    set uploads is uploads",
        "  let upload_count is list length of uploads",
        "  if upload_count is 0:",
        "    try:",
        "      set uploads is state.uploads.chat_files",
        "    with catch err:",
        "      set uploads is uploads",
        "    set upload_count is list length of uploads",
        "  if upload_count is 0:",
        "    try:",
        "      set uploads is state.uploads.intake",
        "    with catch err:",
        "      set uploads is uploads",
        "    set upload_count is list length of uploads",
        "  if upload_count is 0:",
        "    return map:",
        '      "status" is "no_upload"',
        '  find "Project" where id is state.active_project_id',
        '  let active_project_name is "Active Project"',
        "  let active_project_count is list length of project_results",
        "  if active_project_count is greater than 0:",
        "    let active_project is list get project_results at 0",
        "    set active_project_name is active_project.name",
        "  for each upload_item in uploads:",
        '    let upload_id is ""',
        '    let source_name is "Uploaded document"',
        "    try:",
        "      let candidate_upload_id is upload_item.id",
        '      if candidate_upload_id is not "":',
        "        set upload_id is candidate_upload_id",
        "    with catch err:",
        "      set upload_id is upload_id",
        '    if upload_id is "":',
        "      try:",
        "        let fallback_upload_id is upload_item.upload_id",
        '        if fallback_upload_id is not "":',
        "          set upload_id is fallback_upload_id",
        "      with catch err:",
        "        set upload_id is upload_id",
        "    try:",
        "      let candidate_source_name is upload_item.name",
        '      if candidate_source_name is not "":',
        "        set source_name is candidate_source_name",
        "    with catch err:",
        "      set source_name is source_name",
        '    if upload_id is not "":',
        '      let ingestion_out is call pipeline "ingestion":',
        "        input:",
        "          upload_id is upload_id",
        "        output:",
        "          report",
        "          ingestion",
        "          index",
        "      set state.ingestion is ingestion_out.ingestion",
        "      set state.index is ingestion_out.index",
        '      delete "ProjectKnowledgeItem" where id is state.active_project_id + "::" + upload_id',
        '      create "ProjectKnowledgeItem" with map:',
        '        "id" is state.active_project_id + "::" + upload_id',
        '        "project_id" is state.active_project_id',
        '        "project_name" is active_project_name',
        '        "upload_id" is upload_id',
        '        "source_name" is source_name',
        '        "status_label" is "ready"',
        "      as project_knowledge_item",
        "  return map:",
        '    "status" is "ok"',
        "",
        'flow "rag.answer": requires true',
        '  let ensure_status is call flow "rag.ensure_projects":',
        "    input:",
        "    output:",
        "      status",
        '  let query_text is ""',
        "  let has_query is false",
        "  try:",
        "    set query_text is input.message",
        "    set has_query is true",
        "  with catch err:",
        "    set has_query is false",
        "  if has_query is false:",
        "    try:",
        "      set query_text is input.query",
        "      set has_query is true",
        "    with catch err:",
        "      set has_query is false",
        '  if query_text is "":',
        "    try:",
        "      set query_text is input.query_text",
        "      set has_query is true",
        "    with catch err:",
        "      set has_query is has_query",
        "  let question_upload_entries is list:",
        "  let has_pdf_question_upload is false",
        "  try:",
        "    let raw_question_uploads is state.uploads.chat_files",
        "    try:",
        "      for each upload_entry in raw_question_uploads:",
        "        set question_upload_entries is list append question_upload_entries with upload_entry",
        "    with catch err:",
        "      let question_upload_keys is map keys raw_question_uploads",
        "      for each upload_key in question_upload_keys:",
        "        let upload_entry is map get raw_question_uploads key upload_key",
        "        set question_upload_entries is list append question_upload_entries with upload_entry",
        "  with catch err:",
        "    set question_upload_entries is question_upload_entries",
        "  let question_upload_count is list length of question_upload_entries",
        "  if question_upload_count is greater than 0:",
        '    find "Project" where id is state.active_project_id',
        '    let active_project_name is "Active Project"',
        "    let active_project_count is list length of project_results",
        "    if active_project_count is greater than 0:",
        "      let active_project is list get project_results at 0",
        "      set active_project_name is active_project.name",
        "    for each upload_item in question_upload_entries:",
        "      try:",
        "        let upload_content_type is upload_item.type",
        '        if upload_content_type is "application/pdf":',
        "          set has_pdf_question_upload is true",
        "      with catch err:",
        "        set has_pdf_question_upload is has_pdf_question_upload",
        '      let upload_id is ""',
        '      let source_name is "Question attachment"',
        "      try:",
        "        let candidate_upload_id is upload_item.id",
        '        if candidate_upload_id is not "":',
        "          set upload_id is candidate_upload_id",
        "      with catch err:",
        "        set upload_id is upload_id",
        '      if upload_id is "":',
        "        try:",
        "          let fallback_upload_id is upload_item.upload_id",
        '          if fallback_upload_id is not "":',
        "            set upload_id is fallback_upload_id",
        "        with catch err:",
        "          set upload_id is upload_id",
        '      if upload_id is "":',
        "        try:",
        "          let fallback_checksum is upload_item.checksum",
        '          if fallback_checksum is not "":',
        "            set upload_id is fallback_checksum",
        "        with catch err:",
        "          set upload_id is upload_id",
        "      try:",
        "        let candidate_source_name is upload_item.name",
        '        if candidate_source_name is not "":',
        "          set source_name is candidate_source_name",
        "      with catch err:",
        "        set source_name is source_name",
        '      if upload_id is not "":',
        "        try:",
        '          let ingestion_out is call pipeline "ingestion":',
        "            input:",
        "              upload_id is upload_id",
        "            output:",
        "              report",
        "              ingestion",
        "              index",
        "          set state.ingestion is ingestion_out.ingestion",
        "          set state.index is ingestion_out.index",
        "          try:",
        "            let indexed_chunks is map get ingestion_out.index key \"chunks\"",
        "            let indexed_chunk_count is list length of indexed_chunks",
        "            if indexed_chunk_count is greater than 0:",
        "              set has_pdf_question_upload is false",
        "          with catch err:",
        "            set has_pdf_question_upload is has_pdf_question_upload",
        '          delete "ProjectKnowledgeItem" where id is state.active_project_id + "::" + upload_id',
        '          create "ProjectKnowledgeItem" with map:',
        '            "id" is state.active_project_id + "::" + upload_id',
        '            "project_id" is state.active_project_id',
        '            "project_name" is active_project_name',
        '            "upload_id" is upload_id',
        '            "source_name" is source_name',
        '            "status_label" is "ready"',
        "          as question_knowledge_item",
        "        with catch err:",
        "          set state.index is state.index",
        '  let context_text is ""',
        "  let citations is list:",
        '  if has_query and query_text is not "":',
        '    let retrieval_out is call pipeline "retrieval":',
        "      input:",
        "        query is query_text",
        "      output:",
        "        report",
        "    let report is retrieval_out.report",
        "    let results is report.results",
        "    let citation_number is 0",
        "    for each result in results:",
        "      set citation_number is citation_number + 1",
        '      let citation_ref is "[10+]"',
        "      if citation_number is 1:",
        '        set citation_ref is "[1]"',
        "      else:",
        "        if citation_number is 2:",
        '          set citation_ref is "[2]"',
        "        else:",
        "          if citation_number is 3:",
        '            set citation_ref is "[3]"',
        "          else:",
        "            if citation_number is 4:",
        '              set citation_ref is "[4]"',
        "            else:",
        "              if citation_number is 5:",
        '                set citation_ref is "[5]"',
        "              else:",
        "                if citation_number is 6:",
        '                  set citation_ref is "[6]"',
        "                else:",
        "                  if citation_number is 7:",
        '                    set citation_ref is "[7]"',
        "                  else:",
        "                    if citation_number is 8:",
        '                      set citation_ref is "[8]"',
        "                    else:",
        "                      if citation_number is 9:",
        '                        set citation_ref is "[9]"',
        "                      else:",
        "                        if citation_number is 10:",
        '                          set citation_ref is "[10]"',
        '      let context_line is citation_ref + " " + result.text',
        '      if context_text is "":',
        "        set context_text is context_line",
        "      else:",
        '        set context_text is context_text + "\\n" + context_line',
        "      let citation_entry is map:",
        '        "ref" is citation_ref',
        '        "title" is result.source_name',
        '        "source_id" is result.upload_id',
        '        "chunk_id" is result.chunk_id',
        '        "document_id" is result.upload_id',
        '        "page_number" is 1',
        '        "snippet" is result.text',
        '        "url" is result.upload_id',
        '        "preview_url" is "/api/documents/" + result.upload_id + "/pages/1?chunk_id=" + result.chunk_id',
        "      set citations is list append citations with citation_entry",
        '  let __rag_answer_text is ""',
    ]


__all__ = ["build_rag_chat_core_lines"]
