from __future__ import annotations

import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GRAMMAR_PATH = ROOT / "spec" / "grammar" / "namel3ss.grammar"
OUT_PATH = ROOT / "src" / "namel3ss" / "parser" / "generated" / "grammar_snapshot.py"


def main() -> int:
    source = GRAMMAR_PATH.read_text(encoding="utf-8")
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    rules = _collect_rules(source)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(_render_snapshot(digest, rules), encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} ({len(rules)} rules)")
    return 0


def _collect_rules(source: str) -> list[str]:
    rules: list[str] = []
    for raw in source.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        left = line.split("=", 1)[0].strip()
        if left:
            rules.append(left)
    return sorted(set(rules))


def _render_snapshot(digest: str, rules: list[str]) -> str:
    lines = [
        "from __future__ import annotations",
        "",
        "# Generated by tools/generate_parser.py",
        f'GRAMMAR_PATH = "spec/grammar/namel3ss.grammar"',
        f'GRAMMAR_SHA256 = "{digest}"',
        "RULE_NAMES = (",
    ]
    for rule in rules:
        lines.append(f'    "{rule}",')
    lines.extend(
        [
            ")",
            "",
            "__all__ = [\"GRAMMAR_PATH\", \"GRAMMAR_SHA256\", \"RULE_NAMES\"]",
        ]
    )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
