from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from namel3ss.errors.base import Namel3ssError
from namel3ss.errors.guidance import build_guidance_message
from namel3ss.utils.slugify import slugify_text


@dataclass(frozen=True)
class UIPackScaffoldResult:
    target: Path
    files: tuple[str, ...]
    dry_run: bool


def scaffold_ui_pack(name: str, root: Path, *, dry_run: bool = False) -> UIPackScaffoldResult:
    pack_name = _normalize_name(name)
    target = (root / "ui_packs" / pack_name).resolve()
    files = _render_files(pack_name)
    if target.exists():
        raise Namel3ssError(_existing_dir_message(target))
    if dry_run:
        return UIPackScaffoldResult(target=target, files=tuple(sorted(files.keys())), dry_run=True)
    target.mkdir(parents=True, exist_ok=False)
    for rel_path in sorted(files.keys()):
        path = target / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(files[rel_path], encoding="utf-8")
    return UIPackScaffoldResult(target=target, files=tuple(sorted(files.keys())), dry_run=False)


def _normalize_name(value: str) -> str:
    slug = slugify_text(value)
    if slug:
        return slug
    raise Namel3ssError(
        build_guidance_message(
            what="UI pack name is required.",
            why="The create command received an empty name.",
            fix="Pass a non-empty ui_pack name.",
            example="n3 create ui_pack enterprise_dashboard",
        )
    )


def _render_files(name: str) -> dict[str, str]:
    manifest = (
        "{\n"
        f'  "name": "{name}",\n'
        '  "version": "0.1.0",\n'
        '  "kind": "ui_pack",\n'
        '  "description": "UI pack scaffold generated by n3 create ui_pack.",\n'
        "  \"components\": [\n"
        f'    "{name}_panel"\n'
        "  ]\n"
        "}\n"
    )
    component = (
        f'page "{name}_preview":\n'
        "  card:\n"
        '    title is "UI Pack Preview"\n'
        '    text is "Replace this with your reusable UI building block."\n'
    )
    readme = (
        f"# {name}\n\n"
        "Deterministic UI pack scaffold.\n\n"
        "## Layout\n"
        "- `pack.json`: pack metadata.\n"
        "- `components/*.ai`: reusable page/component building blocks.\n\n"
        "## Next steps\n"
        "1. Add additional `components/*.ai` files.\n"
        "2. Keep files deterministic and declarative.\n"
        "3. Reference these blocks in your app templates.\n"
    )
    return {
        "README.md": readme,
        "pack.json": manifest,
        f"components/{name}_panel.ai": component,
    }


def _existing_dir_message(path: Path) -> str:
    return build_guidance_message(
        what=f"Directory already exists: {path.as_posix()}.",
        why="Scaffolding cannot overwrite an existing UI pack directory.",
        fix="Choose a different name or remove the existing folder.",
        example="n3 create ui_pack support_ui",
    )


__all__ = ["UIPackScaffoldResult", "scaffold_ui_pack"]
